"""
Telegram Notification Service for Dellmology Pro
Sends trading alerts and market analysis to Telegram
"""

import os
import json
import logging
import asyncio
from typing import Optional, List, Dict
import httpx

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class TelegramNotifier:
    """Send notifications to Telegram"""

    def __init__(self, bot_token: Optional[str] = None, chat_id: Optional[str] = None):
        self.bot_token = bot_token or os.getenv('TELEGRAM_BOT_TOKEN')
        self.chat_id = chat_id or os.getenv('TELEGRAM_CHAT_ID')
        self.api_url = f"https://api.telegram.org/bot{self.bot_token}"
        
        if not self.bot_token or not self.chat_id:
            logger.warning("Telegram credentials not found. Set TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID")

    async def send_message(self, text: str, parse_mode: str = "HTML") -> bool:
        """
        Send a simple text message to Telegram
        
        Args:
            text: Message text (supports HTML formatting)
            parse_mode: 'HTML' or 'Markdown'
        
        Returns:
            True if successful
        """
        if not self.bot_token or not self.chat_id:
            logger.error("Telegram not configured")
            return False

        try:
            async with httpx.AsyncClient() as client:
                response = await client.post(
                    f"{self.api_url}/sendMessage",
                    json={
                        "chat_id": self.chat_id,
                        "text": text,
                        "parse_mode": parse_mode
                    },
                    timeout=10
                )
                
                if response.status_code == 200:
                    logger.info("Message sent to Telegram")
                    return True
                else:
                    logger.error(f"Telegram API error: {response.status_code}")
                    return False

        except Exception as e:
            logger.error(f"Error sending Telegram message: {e}")
            return False

    async def send_trading_alert(
        self,
        symbol: str,
        signal: str,
        price: float,
        reason: str,
        confidence: int = 75
    ) -> bool:
        """
        Send trading alert message
        
        Args:
            symbol: Stock symbol
            signal: 'BUY', 'SELL', 'STRONG_BUY', 'STRONG_SELL'
            price: Current price
            reason: Why we're sending this alert
            confidence: Confidence level 0-100
        """
        emoji_map = {
            'STRONG_BUY': '🟢🚀',
            'BUY': '🟢',
            'NEUTRAL': '🟡',
            'SELL': '🔴',
            'STRONG_SELL': '🔴⬇️',
        }
        
        emoji = emoji_map.get(signal, '⚪')
        confidence_bar = '█' * (confidence // 10) + '░' * (10 - confidence // 10)

        message = f"""
{emoji} <b>{signal}</b> - {symbol}

<b>Price:</b> Rp {price:,.0f}
<b>Reason:</b> {reason}

<b>Confidence:</b> {confidence}%
{confidence_bar}

<i>Generated by Dellmology Pro</i>
"""
        
        return await self.send_message(message.strip())

    async def send_market_analysis(
        self,
        symbol: str,
        regime: str,
        ups_score: int,
        whale_activity: str,
        recommendation: str
    ) -> bool:
        """Send comprehensive market analysis"""
        emoji_map = {
            'UPTREND': '📈',
            'DOWNTREND': '📉',
            'SIDEWAYS': '➡️',
            'VOLATILE': '⚡',
        }
        
        emoji = emoji_map.get(regime, '🔄')

        message = f"""
{emoji} <b>Market Analysis</b> - {symbol}

<b>Regime:</b> {regime}
<b>UPS Score:</b> {ups_score}/100 {'🟢' if ups_score > 70 else '🟡' if ups_score > 50 else '🔴'}

<b>Whale Activity:</b>
{whale_activity}

<b>Recommendation:</b>
{recommendation}

<i>Powered by Dellmology Pro</i>
"""
        
        return await self.send_message(message.strip())

    async def send_broker_alert(
        self,
        symbol: str,
        broker_id: str,
        net_value: float,
        z_score: float,
        action: str = "ACCUMULATING"
    ) -> bool:
        """Send broker activity alert"""
        emoji = "🐋" if abs(z_score) > 2.5 else "💼"
        color = "🟢" if net_value > 0 else "🔴"

        message = f"""
{emoji} <b>Broker Alert</b> - {symbol}

<b>Broker:</b> {broker_id}
<b>Status:</b> {action} {color}

<b>Net Value:</b> Rp {net_value / 1e9:+.2f}B
<b>Z-Score:</b> {z_score:+.2f}

{("🚨" if z_score > 2.5 else "✓")} {'Whale detected!' if z_score > 2.5 else 'Regular activity'}

<i>Dellmology Pro Broker Monitor</i>
"""
        
        return await self.send_message(message.strip())

    async def send_wash_sale_alert(
        self,
        symbol: str,
        wash_sale_score: float,
        total_volume: int,
        net_accumulation: int
    ) -> bool:
        """Alert about suspicious wash sale patterns"""
        risk_level = "🔴 HIGH" if wash_sale_score > 70 else "🟠 MEDIUM" if wash_sale_score > 50 else "🟢 LOW"

        message = f"""
⚠️ <b>Wash Sale Alert</b> - {symbol}

<b>Risk Level:</b> {risk_level}
<b>Score:</b> {wash_sale_score:.0f}%

<b>Volume:</b> {total_volume:,} lots
<b>Net Accumulation:</b> {net_accumulation:,} lots

<b>Analysis:</b>
High volume but low accumulation = possible manipulation
Proceed with caution!

<i>Dellmology Pro Integrity Shield</i>
"""
        
        return await self.send_message(message.strip())

    async def send_screener_results(
        self,
        mode: str,
        stocks: List[Dict[str, any]],
        timestamp: str
    ) -> bool:
        """Send AI screener results"""
        stocks_text = "\n".join([
            f"#{i+1} {s['symbol']}: Score {s['score']}/100 {s['reason']}"
            for i, s in enumerate(stocks[:5])
        ])

        message = f"""
🤖 <b>AI Screener Report</b>

<b>Mode:</b> {mode}
<b>Time:</b> {timestamp}

{stocks_text}

Use Section 3 for full analysis!

<i>Dellmology Pro AI Screener</i>
"""
        
        return await self.send_message(message.strip())

    async def send_backtest_report(
        self,
        symbol: str,
        win_rate: float,
        total_profit: float,
        sharpe_ratio: float
    ) -> bool:
        """Send backtesting report summary"""
        emoji = "📊"

        message = f"""
{emoji} <b>Backtest Report</b> - {symbol}

<b>Win Rate:</b> {win_rate:.1f}% {'🟢' if win_rate > 50 else '🔴'}
<b>Total P/L:</b> Rp {total_profit:+,.0f}
<b>Sharpe Ratio:</b> {sharpe_ratio:.2f}

✅ Results look {'promising' if sharpe_ratio > 1 else 'needs improvement'}

Check dashboard for full details!

<i>Dellmology Pro Backtester</i>
"""
        
        return await self.send_message(message.strip())


class TelegramAlertManager:
    """Manages alert throttling and scheduling"""

    def __init__(self, notifier: TelegramNotifier):
        self.notifier = notifier
        self.last_alerts: Dict[str, float] = {}  # Track last alert time per symbol
        self.alert_cooldown = 300  # 5 minutes between same alerts for same stock

    async def send_alert_if_cooldown_passed(
        self,
        alert_key: str,
        alert_func,
        *args,
        **kwargs
    ) -> bool:
        """
        Send alert only if cooldown has passed to avoid spam
        
        Args:
            alert_key: Unique identifier for this alert (e.g., 'BBCA_BUY')
            alert_func: Async function to call
            args: Positional arguments for alert_func
            kwargs: Keyword arguments for alert_func
        """
        import time
        
        current_time = time.time()
        last_alert_time = self.last_alerts.get(alert_key, 0)

        if current_time - last_alert_time > self.alert_cooldown:
            success = await alert_func(*args, **kwargs)
            if success:
                self.last_alerts[alert_key] = current_time
            return success
        else:
            logger.info(f"Alert {alert_key} skipped (cooldown active)")
            return False


async def main():
    """Example usage"""
    notifier = TelegramNotifier()

    # Send test alert
    await notifier.send_trading_alert(
        symbol='BBCA',
        signal='STRONG_BUY',
        price=1050.50,
        reason='UPS 85 + Whale accumulation detected',
        confidence=85
    )

    # Send market analysis
    await notifier.send_market_analysis(
        symbol='BBCA',
        regime='UPTREND',
        ups_score=78,
        whale_activity='Broker PD accumulating 5.2B over 7 days',
        recommendation='Good entry point for swing trade. SL: -2.5%'
    )

    # Send broker alert
    await notifier.send_broker_alert(
        symbol='BBCA',
        broker_id='PD',
        net_value=5200000000,
        z_score=3.2,
        action='ACCUMULATING'
    )

    logger.info("Sample alerts sent!")


if __name__ == "__main__":
    asyncio.run(main())
