import { NextResponse } from 'next/server';
import { getSessionValue } from '@/lib/supabase';

export async function GET() {
  try {
    const CACHE_KEY = 'oracle_daily_picks';
    const cachedData = await getSessionValue(CACHE_KEY);

    if (!cachedData) {
      return NextResponse.json({ success: false, error: 'No oracle data found in cache' }, { status: 404 });
    }

    const parsed = JSON.parse(cachedData);
    const picks = parsed.data.topPicks || [];
    const macro = parsed.data.macroSentiment || 'Market sentiment neutral.';

    const botToken = process.env.TELEGRAM_BOT_TOKEN;
    const chatId = process.env.TELEGRAM_CHAT_ID;

    if (!botToken || !chatId) {
      throw new Error('Telegram credentials missing');
    }

    let message = `✨ *Dellmology Oracle Report* ✨\n\n`;
    message += `🌍 *Macro Sentiment:*\n_${macro}_\n\n`;
    message += `🚀 *Top 5 Breakout Picks:*\n\n`;

    picks.forEach((p: any, i: number) => {
      const riskEmoji = p.riskLevel === 'Low' ? '🛡️' : p.riskLevel === 'Medium' ? '⚠️' : '🔥';
      message += `${i + 1}. *${p.emiten}* — Prob: ${p.probability}%\n`;
      message += `   ${riskEmoji} Risk: ${p.riskLevel} | RRR: ${p.rewardToRiskRatio}:1\n`;
      message += `   🎯 Entry: ${p.entryStrategy}\n`;
      message += `   🛑 SL: ${p.stopLoss} | ✅ TP: ${p.takeProfit}\n`;
      message += `   💡 Reason: ${p.reasoning}\n\n`;
    });

    message += `_Generated by Dellmology AI Oracle_`;

    const url = `https://api.telegram.org/bot${botToken}/sendMessage`;
    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        chat_id: chatId,
        text: message,
        parse_mode: 'Markdown',
      }),
    });

    const data = await response.json();

    return NextResponse.json({ success: true, telegram: data });
  } catch (error: any) {
    console.error('Oracle Alert Error:', error);
    return NextResponse.json({ success: false, error: error.message }, { status: 500 });
  }
}
